name: todo_mvc
version: 0.0.2
description: todo_mvc application that uses dartling for its model both on the client and on the server.
author: Dzenan Ridjanovic
homepage: http://ondart.me/
documentation:
dependencies:
  browser: any
  dartling:
    git: 'https://github.com/dzenanr/dartling.git'
  dartling_default_app:
    git: 'https://github.com/dzenanr/dartling_default_app.git'
  